local function config_root()
	return os.getenv("XDG_CONFIG_HOME") or (assert(os.getenv("HOME"), "HOME is not set") .. "/.config")
end

local root = config_root()
package.path = table.concat({
	root .. "/assets/?.lua",
	root .. "/assets/?/init.lua",
	package.path,
}, ";")

local theme = require("theme")

local role_order = {
	"background",
	"panel",
	"panelAlt",
	"text",
	"muted",
	"accent",
	"accentAlt",
	"success",
	"urgent",
	"ornamentText",
	"shadow",
}

local function shell_quote(value)
	return "'" .. value:gsub("'", "'\\''") .. "'"
end

local function ensure_directory(path)
	local ok, _, code = os.execute("mkdir -p " .. shell_quote(path))
	assert(ok, "could not create directory '" .. path .. "' (exit " .. tostring(code) .. ")")
end

local function write_atomic(path, content)
	local directory = path:match("^(.*)/[^/]+$")
	assert(directory, "path has no directory: " .. path)
	ensure_directory(directory)

	local temporary = path .. ".tmp"
	local file, error_message = io.open(temporary, "w")
	assert(file, error_message)
	file:write(content)
	file:close()

	assert(os.rename(temporary, path), "could not replace " .. path)
end

local function hex(color)
	return color.hex
end

local function read_file(path)
	local file, error_message = io.open(path, "r")
	assert(file, error_message)

	local content = file:read("*a")
	file:close()
	return content
end

local function render_quickshell(selected)
	local lines = {
		"pragma Singleton",
		"",
		"import QtQuick",
		"",
		"// Generated by scripts/theme.lua. Do not edit by hand.",
		"QtObject {",
	}

	for _, role in ipairs(role_order) do
		table.insert(lines, "    readonly property color " .. role .. ': "' .. hex(selected.colors[role]) .. '"')
	end

	table.insert(lines, "}")
	return table.concat(lines, "\n") .. "\n"
end

local function render_hypr(selected)
	local lines = {
		"-- Generated by scripts/theme.lua. Do not edit by hand.",
		"local theme = {",
	}

	for _, role in ipairs(role_order) do
		table.insert(lines, "\t" .. role .. ' = { hex = "' .. hex(selected.colors[role]) .. '" },')
	end

	table.insert(lines, "}")
	table.insert(lines, "")
	table.insert(lines, "function theme.hex(name)")
	table.insert(lines, "\tassert(theme[name] and theme[name].hex, \"unknown theme role: \" .. tostring(name))")
	table.insert(lines, "\treturn theme[name].hex")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "function theme.rgba(name, alpha)")
	table.insert(lines, "\tlocal value = theme.hex(name):sub(2)")
	table.insert(lines, "\tlocal aa = (\"%02x\"):format(math.floor(alpha * 255 + 0.5))")
	table.insert(lines, "\treturn \"rgba(\" .. value .. aa .. \")\"")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "function theme.argb(name, alpha)")
	table.insert(lines, "\tlocal value = theme.hex(name):sub(2)")
	table.insert(lines, "\tlocal aa = (\"%02x\"):format(math.floor(alpha * 255 + 0.5))")
	table.insert(lines, "\treturn tonumber(\"0x\" .. aa .. value)")
	table.insert(lines, "end")
	table.insert(lines, "")
	table.insert(lines, "return theme")
	return table.concat(lines, "\n") .. "\n"
end

local function render_rofi(selected)
	return string.format([[/* Generated by scripts/theme.lua. Do not edit by hand. */
* {
  background:     %sFF;
  background-alt: %sFF;
  foreground:     %sFF;
  selected:       %sFF;
  active:         %sFF;
  urgent:         %sFF;
}
]], hex(selected.colors.background), hex(selected.colors.panel), hex(selected.colors.text), hex(selected.colors.accentAlt), hex(selected.colors.success), hex(selected.colors.urgent))
end

local function render_swaync(selected)
	local colors = selected.colors
	return string.format([[/* Generated by scripts/theme.lua. Do not edit by hand. */
@define-color bg0_h %s;
@define-color bg0 %s;
@define-color bg1 %s;
@define-color bg2 %s;
@define-color bg3 %s;
@define-color bg4 %s;

@define-color fg %s;
@define-color fg0 %s;
@define-color fg1 %s;
@define-color fg4 %s;

@define-color aqua %s;
@define-color green %s;
@define-color gray %s;
@define-color blue %s;
@define-color yellow %s;
@define-color red %s;
@define-color ornament %s;
@define-color shadow %s;
]], hex(colors.panel), hex(colors.background), hex(colors.panel), hex(colors.panelAlt), hex(colors.muted), hex(colors.muted), hex(colors.text), hex(colors.text), hex(colors.text), hex(colors.muted), hex(colors.accentAlt), hex(colors.success), hex(colors.muted), hex(colors.accentAlt), hex(colors.accent), hex(colors.urgent), hex(colors.ornamentText), hex(colors.shadow))
end

local function render_kitty(selected)
	local terminal = selected.terminal
	local lines = {
		"# Generated by scripts/theme.lua. Do not edit by hand.",
		"background " .. hex(terminal.background),
		"foreground " .. hex(terminal.foreground),
		"cursor " .. hex(terminal.cursor),
		"cursor_text_color " .. hex(terminal.cursorText),
		"selection_background " .. hex(terminal.selectionBackground),
		"selection_foreground " .. hex(terminal.selectionForeground),
		"",
	}

	for index, color in ipairs(terminal.normal) do
		table.insert(lines, "color" .. (index - 1) .. " " .. hex(color))
	end

	table.insert(lines, "")
	for index, color in ipairs(terminal.bright) do
		table.insert(lines, "color" .. (index + 7) .. " " .. hex(color))
	end

	return table.concat(lines, "\n") .. "\n"
end

local function render_starship(selected)
	local starship_role_names = {
		panelAlt = "panel_alt",
		accentAlt = "accent_alt",
		ornamentText = "ornament_text",
	}
	local palette_lines = {}
	for _, role in ipairs(role_order) do
		local name = starship_role_names[role] or role
		table.insert(palette_lines, name .. ' = "' .. hex(selected.colors[role]) .. '"')
	end

	local prompt_backgrounds = {
		{ name = "prompt_identity_bg", role = "promptIdentity" },
		{ name = "prompt_directory_bg", role = "promptDirectory" },
	}
	for _, prompt_background in ipairs(prompt_backgrounds) do
		local color = selected.colors[prompt_background.role]
		assert(color and color.hex, "missing Starship prompt color: " .. prompt_background.role)
		table.insert(palette_lines, prompt_background.name .. ' = "' .. hex(color) .. '"')
	end

	local layout = read_file(root .. "/starship/layout.toml")
	local output, replacements = layout:gsub("__THEME_PALETTE__", table.concat(palette_lines, "\n"))
	assert(replacements == 1, "starship layout must contain exactly one __THEME_PALETTE__ marker")
	return output
end

local function fastfetch_palette_swatches(palette)
	local swatch_rows = {
		{ "base00", "base01", "base02", "base03", "base04", "base05", "base06", "base07" },
		{ "error", "tertiary_container", "base0a", "base0b", "primary", "primary_container", "tertiary", "base0f" },
	}
	local rows = {}

	for row_index, swatch_row in ipairs(swatch_rows) do
		local swatches = {}
		for _, palette_key in ipairs(swatch_row) do
			local color = palette[palette_key]
			assert(color and color.hex, "missing Fastfetch palette color: " .. palette_key)
			table.insert(swatches, "{#" .. hex(color) .. "}██")
		end
		rows[row_index] = table.concat(swatches)
	end

	return rows
end

local function render_fastfetch(selected)
	local colors = selected.colors
	local swatch_rows = fastfetch_palette_swatches(selected.palette)
	local replacements = {
		{ marker = "__FASTFETCH_ACCENT__", value = hex(colors.accent) },
		{ marker = "__FASTFETCH_ACCENT_ALT__", value = hex(colors.accentAlt) },
		{ marker = "__FASTFETCH_TEXT__", value = hex(colors.text) },
		{ marker = "__FASTFETCH_MUTED__", value = hex(colors.muted) },
		{ marker = "__FASTFETCH_SUCCESS__", value = hex(colors.success) },
		{ marker = "__FASTFETCH_PALETTE_TOP__", value = swatch_rows[1] },
		{ marker = "__FASTFETCH_PALETTE_BOTTOM__", value = swatch_rows[2] },
	}

	local output = read_file(root .. "/fastfetch/layout.jsonc")
	for _, replacement in ipairs(replacements) do
		local count
		output, count = output:gsub(replacement.marker, replacement.value)
		assert(count > 0, "fastfetch layout is missing marker: " .. replacement.marker)
	end

	return output
end

local function render_zsh_highlighting(selected)
	local colors = selected.colors
	return string.format([[# Generated by scripts/theme.lua. Do not edit by hand.
# Source this after zsh-syntax-highlighting has been loaded.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=%s'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=%s,underline'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=%s'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=%s'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=%s,underline'
ZSH_HIGHLIGHT_STYLES[path]='fg=%s,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=%s'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=%s'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=%s'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=%s'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=%s'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=%s'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=%s'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=%s'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=%s'
ZSH_HIGHLIGHT_STYLES[comment]='fg=%s'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=%s,bold'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=%s,bold'
]],
		hex(colors.text),
		hex(colors.accent),
		hex(colors.urgent),
		hex(colors.accentAlt),
		hex(colors.success),
		hex(colors.accentAlt),
		hex(colors.accent),
		hex(colors.muted),
		hex(colors.success),
		hex(colors.text),
		hex(colors.accentAlt),
		hex(colors.accentAlt),
		hex(colors.accentAlt),
		hex(colors.accentAlt),
		hex(colors.accentAlt),
		hex(colors.success),
		hex(colors.success),
		hex(colors.success),
		hex(colors.accent),
		hex(colors.muted),
		hex(colors.urgent),
		hex(colors.accentAlt),
		hex(colors.success),
		hex(colors.accent)
)
end

local function render_state(id)
	return 'return {\n\tactive = "' .. id .. '",\n}\n'
end

local function output_files(selected)
	return {
		{ path = root .. "/Quickshell/theme/Colors.qml", content = render_quickshell(selected) },
		{ path = root .. "/hypr/modules/theme.lua", content = render_hypr(selected) },
		{ path = root .. "/rofi/shared/colors.rasi", content = render_rofi(selected) },
		{ path = root .. "/swaync/colors/active.css", content = render_swaync(selected) },
		{ path = root .. "/kitty/themes/active.conf", content = render_kitty(selected) },
		{ path = root .. "/starship/starship.toml", content = render_starship(selected) },
		{ path = root .. "/fastfetch/config.jsonc", content = render_fastfetch(selected) },
		{ path = root .. "/starship/zsh-theme.zsh", content = render_zsh_highlighting(selected) },
	}
end

local function apply_theme(id)
	local selected = theme.resolve(id)
	for _, output in ipairs(output_files(selected)) do
		write_atomic(output.path, output.content)
	end

	write_atomic(root .. "/assets/theme_state.lua", render_state(selected.id))
	print("Applied theme: " .. selected.name .. " (" .. selected.id .. ")")

	local hypr_ok = os.execute("hyprctl reload >/dev/null 2>&1")
	if hypr_ok then
		print("Reloaded Hyprland")
	else
		io.stderr:write("Theme files generated; Hyprland reload skipped.\n")
	end

	local swaync_ok = os.execute("swaync-client -rs >/dev/null 2>&1")
	if swaync_ok then
		print("Reloaded SwayNC CSS")
	else
		io.stderr:write("Theme files generated; SwayNC CSS reload skipped.\n")
	end

	print("Quickshell reloads its generated colors automatically. New Kitty windows use the active theme.")
end

local function print_usage()
	io.stderr:write("Usage: lua scripts/theme.lua <list|current|apply> [theme-id]\n")
end

local command = arg[1]
if command == "list" then
	local active = theme.current().id
	local ids = {}
	for id in pairs(theme.profiles()) do
		table.insert(ids, id)
	end
	table.sort(ids)
	for _, id in ipairs(ids) do
		local profile = theme.resolve(id)
		print((id == active and "* " or "  ") .. id .. " — " .. profile.name)
	end
elseif command == "current" then
	local selected = theme.current()
	print(selected.id .. " — " .. selected.name)
elseif command == "apply" and arg[2] then
	local ok, error_message = pcall(apply_theme, arg[2])
	if not ok then
		io.stderr:write("Theme apply failed: " .. tostring(error_message) .. "\n")
		os.exit(1)
	end
else
	print_usage()
	os.exit(1)
end
