pragma Singleton

import QtQuick

// Generated by scripts/theme.lua. Do not edit by hand.
QtObject {
    readonly property color background: "#101417"
    readonly property color panel: "#1c2024"
    readonly property color panelAlt: "#262a2e"
    readonly property color text: "#dfe3e7"
    readonly property color muted: "#c1c7ce"
    readonly property color accent: "#92cef5"
    readonly property color accentAlt: "#5cc4ff"
    readonly property color success: "#54d341"
    readonly property color urgent: "#ffb4ab"
    readonly property color ornamentText: "#c7e7ff"
    readonly property color shadow: "#000000"
}
