pragma Singleton

import QtQuick

// Generated by scripts/theme.lua. Do not edit by hand.
QtObject {
    readonly property color background: "#060b1f"
    readonly property color panel: "#0a214f"
    readonly property color panelAlt: "#163d78"
    readonly property color text: "#d9e9f7"
    readonly property color muted: "#8fa9c8"
    readonly property color accent: "#d8ad62"
    readonly property color accentAlt: "#23c8ec"
    readonly property color success: "#4f997b"
    readonly property color urgent: "#d66b7b"
    readonly property color ornamentText: "#9edcff"
    readonly property color shadow: "#060b1f"
}
