background {
    monitor =
    path = ~/Pictures/wallpaper-1.jpg
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center

    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgb(ebdbb2)
    inner_color = rgb(282828)
    font_color = rgb(fbf1c7)

    fade_on_empty = false
    placeholder_text = Password...
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 90
    position = 0, 120
    halign = center
    valign = center
}
