-- Generated by scripts/theme.lua. Do not edit by hand.
local theme = {
	background = { hex = "#101417" },
	panel = { hex = "#1c2024" },
	panelAlt = { hex = "#262a2e" },
	text = { hex = "#dfe3e7" },
	muted = { hex = "#c1c7ce" },
	accent = { hex = "#92cef5" },
	accentAlt = { hex = "#5cc4ff" },
	success = { hex = "#54d341" },
	urgent = { hex = "#ffb4ab" },
	ornamentText = { hex = "#c7e7ff" },
	shadow = { hex = "#000000" },
}

function theme.hex(name)
	assert(theme[name] and theme[name].hex, "unknown theme role: " .. tostring(name))
	return theme[name].hex
end

function theme.rgba(name, alpha)
	local value = theme.hex(name):sub(2)
	local aa = ("%02x"):format(math.floor(alpha * 255 + 0.5))
	return "rgba(" .. value .. aa .. ")"
end

function theme.argb(name, alpha)
	local value = theme.hex(name):sub(2)
	local aa = ("%02x"):format(math.floor(alpha * 255 + 0.5))
	return tonumber("0x" .. aa .. value)
end

return theme
