-- Generated by scripts/theme.lua. Do not edit by hand.
local theme = {
	background = { hex = "#060b1f" },
	panel = { hex = "#0a214f" },
	panelAlt = { hex = "#163d78" },
	text = { hex = "#d9e9f7" },
	muted = { hex = "#8fa9c8" },
	accent = { hex = "#d8ad62" },
	accentAlt = { hex = "#23c8ec" },
	success = { hex = "#4f997b" },
	urgent = { hex = "#d66b7b" },
	ornamentText = { hex = "#9edcff" },
	shadow = { hex = "#060b1f" },
}

function theme.hex(name)
	assert(theme[name] and theme[name].hex, "unknown theme role: " .. tostring(name))
	return theme[name].hex
end

function theme.rgba(name, alpha)
	local value = theme.hex(name):sub(2)
	local aa = ("%02x"):format(math.floor(alpha * 255 + 0.5))
	return "rgba(" .. value .. aa .. ")"
end

function theme.argb(name, alpha)
	local value = theme.hex(name):sub(2)
	local aa = ("%02x"):format(math.floor(alpha * 255 + 0.5))
	return tonumber("0x" .. aa .. value)
end

return theme
